# Generated by Django 5.1.3 on 2024-11-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='Categoria',
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.categoria'),
        ),
    ]
