# Generated by Django 5.1.3 on 2024-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_transacao_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
