# Generated by Django 5.1.3 on 2024-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_transacao_categoria_alter_transacao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
